from __future__ import annotations

import json
from html import escape

from .models import AuditReport


def report_payload(report: AuditReport) -> dict:
    payload = report.model_dump(mode="json")
    payload["summary"] = {"score": report.score, **report.counts}
    return payload


def render_json(report: AuditReport) -> str:
    return json.dumps(report_payload(report), ensure_ascii=False, indent=2)


def render_html(report: AuditReport) -> str:
    counts = report.counts
    styles = """
    :root {
      --ink: #171713;
      --paper: #f3f0e8;
      --acid: #d9ff47;
      --muted: #6f6e67;
      --red: #b42318;
      --amber: #a15c00;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--paper);
      color: var(--ink);
      font: 15px/1.55 system-ui, sans-serif;
    }
    main { width: min(1080px, calc(100% - 40px)); margin: 48px auto 80px; }
    header { border-bottom: 2px solid var(--ink); padding-bottom: 30px; }
    .eyebrow { font: 700 12px monospace; letter-spacing: .14em; }
    h1 {
      font-size: clamp(34px, 5vw, 66px);
      line-height: 1;
      margin: .25em 0;
      overflow-wrap: anywhere;
    }
    .summary {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin: 28px 0;
    }
    .metric {
      background: white;
      border: 1px solid #cbc8be;
      border-radius: 16px;
      padding: 18px;
    }
    .metric b { display: block; font-size: 30px; }
    .score { background: var(--acid); }
    .finding {
      background: white;
      border-left: 7px solid #a3a39a;
      padding: 20px 24px;
      margin: 12px 0;
      border-radius: 10px;
    }
    .finding.error { border-color: var(--red); }
    .finding.warning { border-color: var(--amber); }
    .badge { font: 700 11px monospace; text-transform: uppercase; }
    .category { color: var(--muted); margin-left: 10px; }
    h3 { margin: .45em 0 .15em; font-size: 19px; }
    p { margin: .2em 0; color: #464640; }
    code {
      display: inline-block;
      margin-top: 9px;
      background: #efede6;
      padding: 5px 8px;
      border-radius: 5px;
      overflow-wrap: anywhere;
    }
    footer { margin-top: 36px; color: var(--muted); font-size: 13px; }
    @media (max-width: 680px) {
      .summary { grid-template-columns: repeat(2, 1fr); }
    }
    """
    rows = "".join(
        f"""
        <article class="finding {item.severity.value}">
          <div><span class="badge">{escape(item.severity.value)}</span>
          <span class="category">{escape(item.category)}</span></div>
          <h3>{escape(item.title)}</h3>
          <p>{escape(item.message)}</p>
          {f"<code>{escape(str(item.value))}</code>" if item.value is not None else ""}
        </article>
        """
        for item in report.findings
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>OG Audit — {escape(report.final_url)}</title>
  <style>{styles}</style>
</head>
<body><main>
  <header>
    <div class="eyebrow">ICONCODE / OG AUDIT v{escape(report.tool_version)}</div>
    <h1>{escape(report.final_url)}</h1>
    <div>
      HTTP {report.status_code} · generated {escape(report.generated_at.isoformat())}
    </div>
  </header>
  <section class="summary">
    <div class="metric score"><span>Score</span><b>{report.score}</b></div>
    <div class="metric"><span>Errors</span><b>{counts["error"]}</b></div>
    <div class="metric"><span>Warnings</span><b>{counts["warning"]}</b></div>
    <div class="metric"><span>Info</span><b>{counts["info"]}</b></div>
  </section>
  <section>{rows or "<p>No findings.</p>"}</section>
  <footer>
    Generated by
    <a href="https://github.com/IconcodeAgency/og-audit">IconCode OG Audit</a>.
    Scores are a prioritization aid, not a search-ranking prediction.
  </footer>
</main></body></html>"""
